import type { Metadata } from "next";
import "./globals.css";
import Body from "./Body";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"     suppressHydrationWarning>
    <meta name="referrer" content="no-referrer" />
      <Body children={children}/>
    </html>
  );
}
